    ORG $1000

CURRENT_FOUR_NIBBLES_VAR    EQU    $200
CURRENT_TWO_NIBBLES_VAR     EQU    $750


START:
    MOVEA.L #$AAAA8888, A2
    MOVE.L A2, D4
    MOVE.L D4, CURRENT_FOUR_NIBBLES_VAR
    BRA HEX_TO_ASCII_CHANGER
    MOVE.W A2, D4
    MOVE.W D4, CURRENT_FOUR_NIBBLES_VAR
    BRA HEX_TO_ASCII_CHANGER
    INCLUDE 'hex_ascii.x68'
    INCLUDE 'hex_ascii_jumptable.x68'

DONE:
    SIMHALT
    END START